---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  # out.width = "90%",
  dpi = 300, 
  message = FALSE, 
  warning = FALSE
)

`%>%` <- magrittr::`%>%`
```

# veriler

<!-- badges: start -->
```{r, echo = FALSE, results='asis'}
cat(
  badger::badge_devel("botan/veriler", "blue")
)
```
<!-- badges: end -->

[R for Data Science](<https://r4ds.had.co.nz/>) kitabında kullanılan verilerin Türkçe çevirilerini içerir.

## Yükleme

Paketi indirmek için:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("botan/veriler")
```

## Çeviriler

```{r, echo = FALSE}
specs <- list.files("inst/specs")
all <- purrr::map(file.path("inst", "specs", specs), yaml::read_yaml)
sources <- purrr::map_chr(all, ~ .x$df$source)
pkgs <- tibble::tibble(
  İsim = purrr::map_chr(all, ~ .x$help$usage),
  Başlık = purrr::map_chr(all, ~ .x$help$title),
  Paket = purrr::map_chr(stringr::str_split(sources, "::"), ~ .x[[1]]),
  Veri = purrr::map_chr(stringr::str_split(sources, "::"), ~ .x[[2]])
)

pkgs %>%
  dplyr::arrange(Paket, Veri) %>% 
  knitr::kable()
```

## Örnek

Basit bir örnek:

```{r example}
library(ggplot2)
library(veriler)

dplyr::glimpse(süsen)

ggplot(süsen, aes(çanak_uzunluğu, çanak_genişliği, colour = tür, shape = tür)) +
  geom_point(size = 3.3, alpha = .77) +
  theme_minimal() +
  scale_color_manual(values = c("#0059b3", "#ffcc00", "#80002a")) +
  labs(
    title = "Çanak yaprağı ölçüleri",
    subtitle = "Süsen Setosa, S. Versicolor ve S. Virginica çiçeklerinin çanak yaprağı uzunlukları ve genişlikleri",
    x = "Çanak yaprağı uzunluğu (cm)",
    y = "Çanak yaprağı genişliği (cm)",
    color = "Süsen türleri:",
    shape = "Süsen türleri:"
  ) +
  theme(
    legend.position = c(.6, .85),
    legend.background  = element_rect(linetype = "dashed")
  )
```

## Dahili kodlar

`veriler` paketi içerisinde kullanılan tüm fonksiyonlar ve YAML yapıları, aynı verilerin İspanyolca çevirilerini içeren [`datos`](<https://github.com/cienciadedatos/datos>) paketinden alınmıştır.
